coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 0%
    patch:
      default:
        target: 80%
        
# Add this section below to ignore the un-tested root files
ignore:
  - "ab_detect.ipynb"